### ISSUE TITLE
Not enough char....

### ISSUE THREAD

**Issue by Ndoll1** [VSEScala/Scala-Dining#265]
String for preferences and allergies is limited in character length. Is it possible to double the amount?

I wanted to add that I prefer dishes that are not vegan/vegetarian. A check would also work for me.

**Comment by LenaWil** [comment]
Oh wait, you said double.  
I should have read closer.

**Comment by Ndoll1** [comment]
1000 is also fine. But then check breaking styling bugs explicitly.

**Comment by LenaWil** [comment]
I forgot to close this.
