### ISSUE TITLE
Suggestion: Make a csv export of transactions readable by excel

### ISSUE THREAD

**Issue by Perry26** [VSEScala/Scala-Dining#270]
When creating a csv file for your transaction history, it is not possible to import it into excel with the default settings. Since newer versions of excel don't allow you to change the settings easily anymore (at least not easily enough that I can explain it to people), I propose to alter creditmanagement/csv.py to include the setting dialect='excel' on the csv writer. (https://docs.python.org/3/library/csv.html)

**Comment by mhvis** [comment]
According to the doc page `excel` seems to be the default value. So it might not be fixed with that change. Do you know the specific issue?

**Comment by LenaWil** [comment]
Could it be a localisation issue?

I know the Dutch version and the American version of Excel don't agree on the definition of csv.  
(Microsoft, why‽)

**Comment by mhvis** [comment]
Closing this as stale. Reopen it if necessary.
