### ISSUE TITLE
Add allergen choices

### ISSUE THREAD

**Issue by mhvis** [VSEScala/Scala-Dining#285]
Continuation of #283. The idea is to add a list of choices in the user profile, for the common allergens and common food preferences.

For the allergens we can use the 14 specified [here (EN)](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32011R1169#d1e32-43-1) and [here (NL)](https://eur-lex.europa.eu/legal-content/NL/TXT/HTML/?uri=CELEX:32011R1169#d1e32-43-1) in Annex II. For the preferences/wishes probably vegetarian, vegan, pescetarian. And a 'other' field for the exceptions.

Any input before I might implement it (if I have time)? @DutcherNL @LenaWil @Ndoll1

**Comment by Ndoll1** [comment]
Suggestion for subdevision

14 allergens
Other allergens not in list (pref. in English)

Preferences like vegetarian, vegan and I don't like X things. Same for if vegetarian/vegan plz remove for instance.

**Comment by Ndoll1** [comment]
Suggestion for display
**Overview of all allergens **
![image](https://github.com/VSEScala/Scala-Dining/assets/75546808/90898888-e15d-4787-8908-9c94e6430114)

All allergens noted by people who joined the list. With icons and Dutch/English name. See picture. 
Then a list of other allergens in BOLD. Ideally no duplicate allergens. 

-----------
**Current list with names**
With icons added for selected allergens. 
Other allergens will be displayed here in **BOLD**
Preferences will be visible here, no special treatment font wise.

**Comment by mhvis** [comment]
Thanks. Great suggestions! This would be a good way to implement it.
