### ISSUE TITLE
Change "Kind of dish" option to multi-options instead of a single option

### ISSUE THREAD

**Issue by TimHeiszwolf** [VSEScala/Scala-Dining#288]
Today I noticed this new feature (very nice addition) but I also noticed that you can only pick one of the options while some dishes might feature options. For example when making an AVG meal one might make vega meat for the vega's and real meat for the normal people.

So my suggestion is to impliment a checkbox there (instead of a single option) (or to change the name into "Vegetarian suitable").

**Comment by TimHeiszwolf** [comment]
Also maybe I am stupid (don't use Git(hub) that often) but I can't seem to add a label to this issue.

**Comment by mhvis** [comment]
Yes good point. It might be a bit vague if a meal has both a "vegetarian" and "meat" label. Maybe just some extra options for the mixed cases would do the trick. Something like what you suggested "vegetarian suitable", or maybe "both meat and vegetarian options possible"

@Ndoll1 @LenaWil ideas?

**Comment by mhvis** [comment]
> Also maybe I am stupid (don't use Git(hub) that often) but I can't seem to add a label to this issue.

Yeah that's correct, only repository members can do that.

**Comment by TimHeiszwolf** [comment]
Yeah something like that sounds great! Maybe change it into:
* With meat
* With fish
* Fully vegetarian
* Fully vegan
* Meat or vegetarian
* Meat or vegan

Of course to do do all reasonable combinations you would need 4+2*2(meat/fish+vega/vegan)+1(vega+vegan)=9 options which might be a bit much.

**Comment by Ndoll1** [comment]
Would suggest the following as radiobutton

Contains meat
Contains fish
Vegetarian
Vegan

With optional checkbox
Vegetarian friendly
Vegan friendly
